data_stream:
  host: "localhost"
  port: 3399

lidar_coords:
  lidar_lat: 40.444223
  lidar_lon: -79.958145
  ref_lat: 40.444456
  ref_lon: -79.958182

producer:
  target_url: "http://localhost:3000/"
